#!/bin/sh
#
# LTOAREADIN H5FILE
#
FN=$$
#
YMD=`basename $1 | awk '{print substr($1,8,9)}'`
V=`basename $1 | awk '{print substr($1,22,2)}'`
H=`basename $1 | awk '{print substr($1,24,2)}'`
#
gdalinfo $1 > /tmp/$FN
#
LLAT=`grep Geometry_data_Lower_left_latitude /tmp/$FN | tr '=' ' ' | awk '{print $2}'`
ULAT=`grep Geometry_data_Upper_left_latitude /tmp/$FN | tr '=' ' ' | awk '{print $2}'`
LLNG1=`grep Geometry_data_Lower_left_longitude /tmp/$FN | tr '=' ' ' | awk '{print $2}'`
LLNG2=`grep Geometry_data_Upper_left_longitude /tmp/$FN | tr '=' ' ' | awk '{print $2}'`
LLNG=`echo $LLNG1 $LLNG2 | awk '($1<$2){print $1} ($1>=$2){print $2}'`
RLNG1=`grep Geometry_data_Lower_right_longitude /tmp/$FN | tr '=' ' ' | awk '{print $2}'`
RLNG2=`grep Geometry_data_Upper_right_longitude /tmp/$FN | tr '=' ' ' | awk '{print $2}'`
RLNG=`echo $RLNG1 $RLNG2 | awk '($1<$2){print $2} ($1>=$2){print $1}'`
#
#VN03
#
DD=`grep Image_data_Rs_VN03_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Image_data_Rs_VN03_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Image_data_st_VN03_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD 65535 >> /tmp/P$FN
h5dump -d //Image_data/Rs_VN03 -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_USGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_RVN03" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_RVN03" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#VN05
#
DD=`grep Image_data_Rs_VN05_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Image_data_Rs_VN05_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Image_data_Rs_VN05_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD 65535 >> /tmp/P$FN
h5dump -d //Image_data/Rs_VN05 -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_USGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_RVN05" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_RVN05" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#VN08
#
DD=`grep Image_data_Rs_VN08_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Image_data_Rs_VN08_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Image_data_Rs_VN08_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD 65535 >> /tmp/P$FN
h5dump -d //Image_data/Rs_VN08 -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_USGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_RVN08" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_RVN08" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#SW03
#
DD=`grep Image_data_Rs_SW03_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Image_data_Rs_SW03_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Image_data_Rs_SW03_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD 65535 >> /tmp/P$FN
h5dump -d //Image_data/Rs_SW03 -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_USGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_RSW03" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_RSW03" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#VN11
#
DD=`grep Image_data_Rs_VN11_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Image_data_Rs_VN11_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Image_data_Rs_VN11_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD 65535 >> /tmp/P$FN
h5dump -d //Image_data/Rs_VN11 -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_USGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_RVN11" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_RVN11" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#SW04
#
DD=`grep Image_data_Rs_SW03_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
h5dump -d //Image_data/Rs_SW04 -b LE -o /tmp/D$FN $1
$HOME/SGLI/TOOL2/12to48  /tmp/D$FN >  /tmp/DD$FN
G=`grep Image_data_Rs_SW04_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Image_data_Rs_SW04_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD 65535 >> /tmp/P$FN
echo /tmp/DD$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_USGO /tmp/P$FN > /tmp/S$FN
XLRECL=`$HOME/SGLI/TOOL2/48to12 /tmp/S$FN $LLRECL   /tmp/DDD$FN`
r.in.bin -d input=/tmp/DDD$FN output="SV"$V"H"$H"_"$YMD"_RSW04" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=1200 cols=$XLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_RSW04" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN  /tmp/DD$FN /tmp/DDD$FN
#
#TI01
#
DD=`grep Image_data_Tb_TI01_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Image_data_Tb_TI01_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Image_data_Tb_TI01_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD 65535 >> /tmp/P$FN
h5dump -d //Image_data/Tb_TI01 -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_USGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_TB01" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_TB01" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#TI02
#
DD=`grep Image_data_Tb_TI02_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Image_data_Tb_TI02_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Image_data_Tb_TI02_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD 65535 >> /tmp/P$FN
h5dump -d //Image_data/Tb_TI02 -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_USGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_TB02" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_TB02" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#SeZ
#
#DD=`grep Geometry_data_Sensor_zenith_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
#LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Geometry_data_Sensor_zenith_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Geometry_data_Sensor_zenith_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD -32768 >> /tmp/P$FN
h5dump -d //Geometry_data/Sensor_zenith -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_SGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_SeZ" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_SeZ" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#SeA
#
#DD=`grep Geometry_data_Sensor_zenith_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
#LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Geometry_data_Sensor_azimuth_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Geometry_data_Sensor_azimuth_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD -32768 >> /tmp/P$FN
h5dump -d //Geometry_data/Sensor_azimuth -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_SGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_SeA" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_SeA" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#SoA
#
#DD=`grep Geometry_data_Solar_zenith_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
#LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Geometry_data_Solar_azimuth_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Geometry_data_Solar_azimuth_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD -32768 >> /tmp/P$FN
h5dump -d //Geometry_data/Solar_azimuth -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_SGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_SoA" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_SoA" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#SZA
#
#DD=`grep Geometry_data_Solar_zenith_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
#LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Geometry_data_Solar_zenith_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Geometry_data_Solar_zenith_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD -32768 >> /tmp/P$FN
h5dump -d //Geometry_data/Solar_zenith -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_SGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_SZA" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_SZA" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#OBSTIME
#
#DD=`grep Geometry_data_Solar_zenith_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
#LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
G=`grep Geometry_data_Obs_time_Slope= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
O=`grep Geometry_data_Obs_time_Offset= /tmp/$FN  | tr '=' ' '| awk '{print $2}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD -32768 >> /tmp/P$FN
h5dump -d //Geometry_data/Obs_time -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_SGO /tmp/P$FN > /tmp/S$FN
r.in.bin -d input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_TIM" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=-500
r.colors map="SV"$V"H"$H"_"$YMD"_TIM" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
#LAND/WATERFLAG
#
#DD=`grep Geometry_data_Solar_zenith_Spatial_resolution= /tmp/$FN | head -1 | tr '=' ' ' | awk '{print $2}'`
#LLRECL=`echo $LLNG $RLNG $DD | awk '{print int(0.5+($2-$1)/$3)}'`
echo 4800 4800 > /tmp/P$FN
echo $LLRECL 4800 >> /tmp/P$FN
echo $H $V >> /tmp/P$FN
echo $ULAT $LLAT $RLNG $LLNG $DD 255 >> /tmp/P$FN
h5dump -d //Image_data/Land_water_flag -b LE -o /tmp/D$FN $1
echo /tmp/D$FN >> /tmp/P$FN
echo $G $O >> /tmp/P$FN
$HOME/SGLI/TOOL2/SIN2LL_UC /tmp/P$FN > /tmp/S$FN
r.in.bin bytes=1 input=/tmp/S$FN output="SV"$V"H"$H"_"$YMD"_LW" n=$ULAT s=$LLAT w=$LLNG e=$RLNG rows=4800 cols=$LLRECL anull=255
r.colors map="SV"$V"H"$H"_"$YMD"_LW" color=grey
rm /tmp/P$FN /tmp/D$FN /tmp/S$FN
#
rm /tmp/$FN
